<a href="https://colab.research.google.com/github/lifeisawavesorideit/99_LEARN_jvns_pandas-cookbook/blob/master/Chapter07.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
%matplotlib inline

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

# Make the graphs a bit prettier, and bigger
plt.style.use('ggplot')
plt.rcParams['figure.figsize'] = (15, 5)
plt.rcParams['font.family'] = 'sans-serif'

# This is necessary to show lots of columns in pandas 0.12. 
# Not necessary in pandas 0.13.
pd.set_option('display.width', 5000) 
pd.set_option('display.max_columns', 60)

In [4]:
csv_path = 'https://raw.githubusercontent.com/lifeisawavesorideit/99_LEARN_jvns_pandas-cookbook/master/data/311-service-requests.csv'

In [8]:
df = pd.read_csv(csv_path, sep=',', dtype='unicode')
df

       Unique Key            Created Date             Closed Date Agency                              Agency Name           Complaint Type                     Descriptor        Location Type Incident Zip      Incident Address      Street Name      Cross Street 1                    Cross Street 2   Intersection Street 1 Intersection Street 2  Address Type      City Landmark Facility Type    Status                Due Date Resolution Action Updated Date Community Board    Borough X Coordinate (State Plane) Y Coordinate (State Plane) Park Facility Name Park Borough  School Name School Number School Region  School Code School Phone Number                                     School Address  School City School State   School Zip School Not Found School or Citywide Complaint Vehicle Type Taxi Company Borough Taxi Pick Up Location Bridge Highway Name Bridge Highway Direction Road Ramp Bridge Highway Segment Garage Lot Name Ferry Direction Ferry Terminal Name            Latitude           Longitude                                  Location
0        26589651  10/31/2013 02:08:41 AM                     NaN   NYPD          New York City Police Department  Noise - Street/Sidewalk                   Loud Talking      Street/Sidewalk        11432      90-03 169 STREET       169 STREET           90 AVENUE                         91 AVENUE                     NaN                   NaN       ADDRESS   JAMAICA      NaN      Precinct  Assigned  10/31/2013 10:08:41 AM         10/31/2013 02:35:17 AM       12 QUEENS     QUEENS                    1042027                     197389        Unspecified       QUEENS  Unspecified   Unspecified   Unspecified  Unspecified         Unspecified                                        Unspecified  Unspecified  Unspecified  Unspecified                N                          NaN          NaN                  NaN                   NaN                 NaN                      NaN       NaN                    NaN             NaN             NaN                 NaN   40.70827532593202  -73.79160395779721   (40.70827532593202, -73.79160395779721)
1        26593698  10/31/2013 02:01:04 AM                     NaN   NYPD          New York City Police Department          Illegal Parking   Commercial Overnight Parking      Street/Sidewalk        11378             58 AVENUE        58 AVENUE            58 PLACE                         59 STREET                     NaN                   NaN     BLOCKFACE   MASPETH      NaN      Precinct      Open  10/31/2013 10:01:04 AM                            NaN       05 QUEENS     QUEENS                    1009349                     201984        Unspecified       QUEENS  Unspecified   Unspecified   Unspecified  Unspecified         Unspecified                                        Unspecified  Unspecified  Unspecified  Unspecified                N                          NaN          NaN                  NaN                   NaN                 NaN                      NaN       NaN                    NaN             NaN             NaN                 NaN  40.721040535628305  -73.90945306791765  (40.721040535628305, -73.90945306791765)
2        26594139  10/31/2013 02:00:24 AM  10/31/2013 02:40:32 AM   NYPD          New York City Police Department       Noise - Commercial               Loud Music/Party  Club/Bar/Restaurant        10032         4060 BROADWAY         BROADWAY     WEST 171 STREET                   WEST 172 STREET                     NaN                   NaN       ADDRESS  NEW YORK      NaN      Precinct    Closed  10/31/2013 10:00:24 AM         10/31/2013 02:39:42 AM    12 MANHATTAN  MANHATTAN                    1001088                     246531        Unspecified    MANHATTAN  Unspecified   Unspecified   Unspecified  Unspecified         Unspecified                                        Unspecified  Unspecified  Unspecified  Unspecified                N                          NaN          NaN                  NaN                   NaN                 NaN                      NaN       NaN                    NaN             NaN             NaN                 NaN   40.84332975466513  -73.93914371913482   (40.84332975466513, -73.93914371913482)
3        26595721  10/31/2013 01:56:23 AM  10/31/2013 02:21:48 AM   NYPD          New York City Police Department          Noise - Vehicle                 Car/Truck Horn      Street/Sidewalk        10023        WEST 72 STREET   WEST 72 STREET     COLUMBUS AVENUE                  AMSTERDAM AVENUE                     NaN                   NaN     BLOCKFACE  NEW YORK      NaN      Precinct    Closed  10/31/2013 09:56:23 AM         10/31/2013 02:21:10 AM    07 MANHATTAN  MANHATTAN                     989730                     222727        Unspecified    MANHATTAN  Unspecified   Unspecified   Unspecified  Unspecified         Unspecified                                        Unspecified  Unspecified  Unspecified  Unspecified                N                          NaN          NaN                  NaN                   NaN                 NaN                      NaN       NaN                    NaN             NaN             NaN                 NaN    40.7780087446372  -73.98021349023975    (40.7780087446372, -73.98021349023975)
4        26590930  10/31/2013 01:53:44 AM                     NaN  DOHMH  Department of Health and Mental Hygiene                   Rodent   Condition Attracting Rodents           Vacant Lot        10027       WEST 124 STREET  WEST 124 STREET        LENOX AVENUE  ADAM CLAYTON POWELL JR BOULEVARD                     NaN                   NaN     BLOCKFACE  NEW YORK      NaN           NaN   Pending  11/30/2013 01:53:44 AM         10/31/2013 01:59:54 AM    10 MANHATTAN  MANHATTAN                     998815                     233545        Unspecified    MANHATTAN  Unspecified   Unspecified   Unspecified  Unspecified         Unspecified                                        Unspecified  Unspecified  Unspecified  Unspecified                N                          NaN          NaN                  NaN                   NaN                 NaN                      NaN       NaN                    NaN             NaN             NaN                 NaN   40.80769092704951  -73.94738703491433   (40.80769092704951, -73.94738703491433)
...           ...                     ...                     ...    ...                                      ...                      ...                            ...                  ...          ...                   ...              ...                 ...                               ...                     ...                   ...           ...       ...      ...           ...       ...                     ...                            ...             ...        ...                        ...                        ...                ...          ...          ...           ...           ...          ...                 ...                                                ...          ...          ...          ...              ...                          ...          ...                  ...                   ...                 ...                      ...       ...                    ...             ...             ...                 ...                 ...                 ...                                       ...
111064   26426013  10/04/2013 12:01:13 AM  10/07/2013 04:07:16 PM    DPR       Department of Parks and Recreation  Maintenance or Facility           Structure - Outdoors                 Park        11213                   NaN              NaN                 NaN                               NaN                     NaN                   NaN           NaN  BROOKLYN      NaN           NaN    Closed  10/18/2013 12:01:13 AM         10/07/2013 04:07:16 PM     08 BROOKLYN   BROOKLYN                        NaN                        NaN        Brower Park     BROOKLYN  Brower Park          B012           NaN          NaN          7189658900  Brooklyn, St. Marks, Kingston Avenues, Park Place     BROOKLYN           NY        11213                N                          NaN          NaN                  NaN                   NaN                 NaN                      NaN       NaN                    NaN             NaN             NaN                 NaN                 NaN                 NaN                                       NaN
111065   26428083  10/04/2013 12:01:05 AM  10/04/2013 02:13:50 AM   NYPD          New York City Police Department          Illegal Parking  Posted Parking Sign Violation      Street/Sidewalk        11434                   NaN              NaN                 NaN                               NaN  GUY R BREWER BOULEVARD    ROCKAWAY BOULEVARD  INTERSECTION   JAMAICA      NaN      Precinct    Closed  10/04/2013 08:01:05 AM         10/04/2013 02:13:50 AM       13 QUEENS     QUEENS                    1048801                     178419        Unspecified       QUEENS  Unspecified   Unspecified   Unspecified  Unspecified         Unspecified                                        Unspecified  Unspecified  Unspecified  Unspecified                N                          NaN          NaN                  NaN                   NaN                 NaN                      NaN       NaN                    NaN             NaN             NaN                 NaN  40.656160351546845  -73.76735262738222  (40.656160351546845, -73.76735262738222)
111066   26428987  10/04/2013 12:00:45 AM  10/04/2013 01:25:01 AM   NYPD          New York City Police Department  Noise - Street/Sidewalk                   Loud Talking      Street/Sidewalk        10016    344 EAST 28 STREET   EAST 28 STREET  MOUNT CARMEL PLACE                          1 AVENUE                     NaN                   NaN       ADDRESS  NEW YORK      NaN      Precinct    Closed  10/04/2013 08:00:45 AM         10/04/2013 01:25:01 AM    06 MANHATTAN  MANHATTAN                     990637                     208987        Unspecified    MANHATTAN  Unspecified   Unspecified   Unspecified  Unspecified         Unspecified                                        Unspecified  Unspecified  Unspecified  Unspecified                N                          NaN          NaN                  NaN                   NaN                 NaN                      NaN       NaN                    NaN             NaN             NaN                 NaN  40.740295354643706  -73.97695165980414  (40.740295354643706, -73.97695165980414)
111067   26426115  10/04/2013 12:00:28 AM  10/04/2013 04:17:32 AM   NYPD          New York City Police Department       Noise - Commercial                   Loud Talking  Club/Bar/Restaurant        11226  1233 FLATBUSH AVENUE  FLATBUSH AVENUE            AVENUE D                    NEWKIRK AVENUE                     NaN                   NaN       ADDRESS  BROOKLYN      NaN      Precinct    Closed  10/04/2013 08:00:28 AM         10/04/2013 04:17:32 AM     14 BROOKLYN   BROOKLYN                     996654                     172515        Unspecified     BROOKLYN  Unspecified   Unspecified   Unspecified  Unspecified         Unspecified                                        Unspecified  Unspecified  Unspecified  Unspecified                N                          NaN          NaN                  NaN                   NaN                 NaN                      NaN       NaN                    NaN             NaN             NaN                 NaN   40.64018174662485  -73.95530566958138   (40.64018174662485, -73.95530566958138)
111068   26428033  10/04/2013 12:00:10 AM  10/04/2013 01:20:52 AM   NYPD          New York City Police Department         Blocked Driveway                 Partial Access      Street/Sidewalk        11236   1259 EAST 94 STREET   EAST 94 STREET            AVENUE J                          AVENUE K                     NaN                   NaN       ADDRESS  BROOKLYN      NaN      Precinct    Closed  10/04/2013 08:00:10 AM         10/04/2013 01:20:52 AM     18 BROOKLYN   BROOKLYN                    1011804                     172470        Unspecified     BROOKLYN  Unspecified   Unspecified   Unspecified  Unspecified         Unspecified                                        Unspecified  Unspecified  Unspecified  Unspecified                N                          NaN          NaN                  NaN                   NaN                 NaN                      NaN       NaN                    NaN             NaN             NaN                 NaN  40.640024057399216  -73.90071711703163  (40.640024057399216, -73.90071711703163)

[111069 rows x 52 columns]

In [27]:
df['Incident Zip'].unique()

array(['11432', '11378', '10032', '10023', '10027', '11372', '11419',
       '11417', '10011', '11225', '11218', '10003', '10029', '10466',
       '11219', '10025', '10310', '11236', nan, '10033', '11216', '10016',
       '10305', '10312', '10026', '10309', '10036', '11433', '11235',
       '11213', '11379', '11101', '10014', '11231', '11234', '10457',
       '10459', '10465', '11207', '10002', '10034', '11233', '10453',
       '10456', '10469', '11374', '11221', '11421', '11215', '10007',
       '10019', '11205', '11418', '11369', '11249', '10005', '10009',
       '11211', '11412', '10458', '11229', '10065', '10030', '11222',
       '10024', '10013', '11420', '11365', '10012', '11214', '11212',
       '10022', '11232', '11040', '11226', '10281', '11102', '11208',
       '10001', '10472', '11414', '11223', '10040', '11220', '11373',
       '11203', '11691', '11356', '10017', '10452', '10280', '11217',
       '10031', '11201', '11358', '10128', '11423', '10039', '10010',
       '11209', '10021', '10037', '11413', '11375', '11238', '10473',
       '11103', '11354', '11361', '11106', '11385', '10463', '10467',
       '11204', '11237', '11377', '11364', '11434', '11435', '11210',
       '11228', '11368', '11694', '10464', '11415', '10314', '10301',
       '10018', '10038', '11105', '11230', '10468', '11104', '10471',
       '11416', '10075', '11422', '11355', '10028', '10462', '10306',
       '10461', '11224', '11429', '10035', '11366', '11362', '11206',
       '10460', '10304', '11360', '11411', '10455', '10475', '10069',
       '10303', '10308', '10302', '11357', '10470', '11367', '11370',
       '10454', '10451', '11436', '11426', '10153', '11004', '11428',
       '11427', '11001', '11363', '10004', '10474', '11430', '10000',
       '10307', '11239', '10119', '10006', '10048', '11697', '11692',
       '11693', '10573', '00083', '11559', '10020', '77056', '11776',
       '70711', '10282', '11109', '10044', '02061', '77092-2016', '14225',
       '55164-0737', '19711', '07306', '000000', 'NO CLUE', '90010',
       '11747', '23541', '11788', '07604', '10112', '11563', '11580',
       '07087', '11042', '07093', '11501', '92123', '00000', '11575',
       '07109', '11797', '10803', '11716', '11722', '11549-3650', '10162',
       '23502', '11518', '07020', '08807', '11577', '07114', '11003',
       '07201', '61702', '10103', '29616-0759', '35209-3114', '11520',
       '11735', '10129', '11005', '41042', '11590', '06901', '07208',
       '11530', '13221', '10954', '11111', '10107'], dtype=object)

In [28]:
type(df['Incident Zip'])

pandas.core.series.Series

In [30]:
type(df[['Incident Zip']])

pandas.core.frame.DataFrame

In [43]:
df[['Incident Zip']].value_counts()

Incident Zip
11226           1996
10467           1628
10458           1542
11233           1385
11207           1355
                ...
11520              1
11530              1
11549-3650         1
11559              1
NO CLUE            1
Length: 248, dtype: int64

# 7.2 Fixing the nan values and string/float confusion

In [44]:
na_values = ['NO CLUE', 'N/A', '0']
df = pd.read_csv(csv_path, sep=',', na_values=na_values, dtype={'Incident Zip': str})

In [45]:
df

        Unique Key            Created Date             Closed Date Agency                              Agency Name           Complaint Type                     Descriptor        Location Type Incident Zip      Incident Address      Street Name      Cross Street 1                    Cross Street 2   Intersection Street 1 Intersection Street 2  Address Type      City Landmark Facility Type    Status                Due Date Resolution Action Updated Date Community Board    Borough  X Coordinate (State Plane)  Y Coordinate (State Plane) Park Facility Name Park Borough  School Name School Number School Region  School Code School Phone Number                                     School Address  School City School State   School Zip School Not Found  School or Citywide Complaint Vehicle Type Taxi Company Borough Taxi Pick Up Location Bridge Highway Name Bridge Highway Direction Road Ramp Bridge Highway Segment Garage Lot Name Ferry Direction Ferry Terminal Name   Latitude  Longitude                                  Location
0         26589651  10/31/2013 02:08:41 AM                     NaN   NYPD          New York City Police Department  Noise - Street/Sidewalk                   Loud Talking      Street/Sidewalk        11432      90-03 169 STREET       169 STREET           90 AVENUE                         91 AVENUE                     NaN                   NaN       ADDRESS   JAMAICA      NaN      Precinct  Assigned  10/31/2013 10:08:41 AM         10/31/2013 02:35:17 AM       12 QUEENS     QUEENS                   1042027.0                    197389.0        Unspecified       QUEENS  Unspecified   Unspecified   Unspecified  Unspecified         Unspecified                                        Unspecified  Unspecified  Unspecified  Unspecified                N                           NaN          NaN                  NaN                   NaN                 NaN                      NaN       NaN                    NaN             NaN             NaN                 NaN  40.708275 -73.791604   (40.70827532593202, -73.79160395779721)
1         26593698  10/31/2013 02:01:04 AM                     NaN   NYPD          New York City Police Department          Illegal Parking   Commercial Overnight Parking      Street/Sidewalk        11378             58 AVENUE        58 AVENUE            58 PLACE                         59 STREET                     NaN                   NaN     BLOCKFACE   MASPETH      NaN      Precinct      Open  10/31/2013 10:01:04 AM                            NaN       05 QUEENS     QUEENS                   1009349.0                    201984.0        Unspecified       QUEENS  Unspecified   Unspecified   Unspecified  Unspecified         Unspecified                                        Unspecified  Unspecified  Unspecified  Unspecified                N                           NaN          NaN                  NaN                   NaN                 NaN                      NaN       NaN                    NaN             NaN             NaN                 NaN  40.721041 -73.909453  (40.721040535628305, -73.90945306791765)
2         26594139  10/31/2013 02:00:24 AM  10/31/2013 02:40:32 AM   NYPD          New York City Police Department       Noise - Commercial               Loud Music/Party  Club/Bar/Restaurant        10032         4060 BROADWAY         BROADWAY     WEST 171 STREET                   WEST 172 STREET                     NaN                   NaN       ADDRESS  NEW YORK      NaN      Precinct    Closed  10/31/2013 10:00:24 AM         10/31/2013 02:39:42 AM    12 MANHATTAN  MANHATTAN                   1001088.0                    246531.0        Unspecified    MANHATTAN  Unspecified   Unspecified   Unspecified  Unspecified         Unspecified                                        Unspecified  Unspecified  Unspecified  Unspecified                N                           NaN          NaN                  NaN                   NaN                 NaN                      NaN       NaN                    NaN             NaN             NaN                 NaN  40.843330 -73.939144   (40.84332975466513, -73.93914371913482)
3         26595721  10/31/2013 01:56:23 AM  10/31/2013 02:21:48 AM   NYPD          New York City Police Department          Noise - Vehicle                 Car/Truck Horn      Street/Sidewalk        10023        WEST 72 STREET   WEST 72 STREET     COLUMBUS AVENUE                  AMSTERDAM AVENUE                     NaN                   NaN     BLOCKFACE  NEW YORK      NaN      Precinct    Closed  10/31/2013 09:56:23 AM         10/31/2013 02:21:10 AM    07 MANHATTAN  MANHATTAN                    989730.0                    222727.0        Unspecified    MANHATTAN  Unspecified   Unspecified   Unspecified  Unspecified         Unspecified                                        Unspecified  Unspecified  Unspecified  Unspecified                N                           NaN          NaN                  NaN                   NaN                 NaN                      NaN       NaN                    NaN             NaN             NaN                 NaN  40.778009 -73.980213    (40.7780087446372, -73.98021349023975)
4         26590930  10/31/2013 01:53:44 AM                     NaN  DOHMH  Department of Health and Mental Hygiene                   Rodent   Condition Attracting Rodents           Vacant Lot        10027       WEST 124 STREET  WEST 124 STREET        LENOX AVENUE  ADAM CLAYTON POWELL JR BOULEVARD                     NaN                   NaN     BLOCKFACE  NEW YORK      NaN           NaN   Pending  11/30/2013 01:53:44 AM         10/31/2013 01:59:54 AM    10 MANHATTAN  MANHATTAN                    998815.0                    233545.0        Unspecified    MANHATTAN  Unspecified   Unspecified   Unspecified  Unspecified         Unspecified                                        Unspecified  Unspecified  Unspecified  Unspecified                N                           NaN          NaN                  NaN                   NaN                 NaN                      NaN       NaN                    NaN             NaN             NaN                 NaN  40.807691 -73.947387   (40.80769092704951, -73.94738703491433)
...            ...                     ...                     ...    ...                                      ...                      ...                            ...                  ...          ...                   ...              ...                 ...                               ...                     ...                   ...           ...       ...      ...           ...       ...                     ...                            ...             ...        ...                         ...                         ...                ...          ...          ...           ...           ...          ...                 ...                                                ...          ...          ...          ...              ...                           ...          ...                  ...                   ...                 ...                      ...       ...                    ...             ...             ...                 ...        ...        ...                                       ...
111064    26426013  10/04/2013 12:01:13 AM  10/07/2013 04:07:16 PM    DPR       Department of Parks and Recreation  Maintenance or Facility           Structure - Outdoors                 Park        11213                   NaN              NaN                 NaN                               NaN                     NaN                   NaN           NaN  BROOKLYN      NaN           NaN    Closed  10/18/2013 12:01:13 AM         10/07/2013 04:07:16 PM     08 BROOKLYN   BROOKLYN                         NaN                         NaN        Brower Park     BROOKLYN  Brower Park          B012           NaN          NaN          7189658900  Brooklyn, St. Marks, Kingston Avenues, Park Place     BROOKLYN           NY        11213                N                           NaN          NaN                  NaN                   NaN                 NaN                      NaN       NaN                    NaN             NaN             NaN                 NaN        NaN        NaN                                       NaN
111065    26428083  10/04/2013 12:01:05 AM  10/04/2013 02:13:50 AM   NYPD          New York City Police Department          Illegal Parking  Posted Parking Sign Violation      Street/Sidewalk        11434                   NaN              NaN                 NaN                               NaN  GUY R BREWER BOULEVARD    ROCKAWAY BOULEVARD  INTERSECTION   JAMAICA      NaN      Precinct    Closed  10/04/2013 08:01:05 AM         10/04/2013 02:13:50 AM       13 QUEENS     QUEENS                   1048801.0                    178419.0        Unspecified       QUEENS  Unspecified   Unspecified   Unspecified  Unspecified         Unspecified                                        Unspecified  Unspecified  Unspecified  Unspecified                N                           NaN          NaN                  NaN                   NaN                 NaN                      NaN       NaN                    NaN             NaN             NaN                 NaN  40.656160 -73.767353  (40.656160351546845, -73.76735262738222)
111066    26428987  10/04/2013 12:00:45 AM  10/04/2013 01:25:01 AM   NYPD          New York City Police Department  Noise - Street/Sidewalk                   Loud Talking      Street/Sidewalk        10016    344 EAST 28 STREET   EAST 28 STREET  MOUNT CARMEL PLACE                          1 AVENUE                     NaN                   NaN       ADDRESS  NEW YORK      NaN      Precinct    Closed  10/04/2013 08:00:45 AM         10/04/2013 01:25:01 AM    06 MANHATTAN  MANHATTAN                    990637.0                    208987.0        Unspecified    MANHATTAN  Unspecified   Unspecified   Unspecified  Unspecified         Unspecified                                        Unspecified  Unspecified  Unspecified  Unspecified                N                           NaN          NaN                  NaN                   NaN                 NaN                      NaN       NaN                    NaN             NaN             NaN                 NaN  40.740295 -73.976952  (40.740295354643706, -73.97695165980414)
111067    26426115  10/04/2013 12:00:28 AM  10/04/2013 04:17:32 AM   NYPD          New York City Police Department       Noise - Commercial                   Loud Talking  Club/Bar/Restaurant        11226  1233 FLATBUSH AVENUE  FLATBUSH AVENUE            AVENUE D                    NEWKIRK AVENUE                     NaN                   NaN       ADDRESS  BROOKLYN      NaN      Precinct    Closed  10/04/2013 08:00:28 AM         10/04/2013 04:17:32 AM     14 BROOKLYN   BROOKLYN                    996654.0                    172515.0        Unspecified     BROOKLYN  Unspecified   Unspecified   Unspecified  Unspecified         Unspecified                                        Unspecified  Unspecified  Unspecified  Unspecified                N                           NaN          NaN                  NaN                   NaN                 NaN                      NaN       NaN                    NaN             NaN             NaN                 NaN  40.640182 -73.955306   (40.64018174662485, -73.95530566958138)
111068    26428033  10/04/2013 12:00:10 AM  10/04/2013 01:20:52 AM   NYPD          New York City Police Department         Blocked Driveway                 Partial Access      Street/Sidewalk        11236   1259 EAST 94 STREET   EAST 94 STREET            AVENUE J                          AVENUE K                     NaN                   NaN       ADDRESS  BROOKLYN      NaN      Precinct    Closed  10/04/2013 08:00:10 AM         10/04/2013 01:20:52 AM     18 BROOKLYN   BROOKLYN                   1011804.0                    172470.0        Unspecified     BROOKLYN  Unspecified   Unspecified   Unspecified  Unspecified         Unspecified                                        Unspecified  Unspecified  Unspecified  Unspecified                N                           NaN          NaN                  NaN                   NaN                 NaN                      NaN       NaN                    NaN             NaN             NaN                 NaN  40.640024 -73.900717  (40.640024057399216, -73.90071711703163)

[111069 rows x 52 columns]

In [46]:
df['Incident Zip'].unique()

array(['11432', '11378', '10032', '10023', '10027', '11372', '11419',
       '11417', '10011', '11225', '11218', '10003', '10029', '10466',
       '11219', '10025', '10310', '11236', nan, '10033', '11216', '10016',
       '10305', '10312', '10026', '10309', '10036', '11433', '11235',
       '11213', '11379', '11101', '10014', '11231', '11234', '10457',
       '10459', '10465', '11207', '10002', '10034', '11233', '10453',
       '10456', '10469', '11374', '11221', '11421', '11215', '10007',
       '10019', '11205', '11418', '11369', '11249', '10005', '10009',
       '11211', '11412', '10458', '11229', '10065', '10030', '11222',
       '10024', '10013', '11420', '11365', '10012', '11214', '11212',
       '10022', '11232', '11040', '11226', '10281', '11102', '11208',
       '10001', '10472', '11414', '11223', '10040', '11220', '11373',
       '11203', '11691', '11356', '10017', '10452', '10280', '11217',
       '10031', '11201', '11358', '10128', '11423', '10039', '10010',
       '11209', '10021', '10037', '11413', '11375', '11238', '10473',
       '11103', '11354', '11361', '11106', '11385', '10463', '10467',
       '11204', '11237', '11377', '11364', '11434', '11435', '11210',
       '11228', '11368', '11694', '10464', '11415', '10314', '10301',
       '10018', '10038', '11105', '11230', '10468', '11104', '10471',
       '11416', '10075', '11422', '11355', '10028', '10462', '10306',
       '10461', '11224', '11429', '10035', '11366', '11362', '11206',
       '10460', '10304', '11360', '11411', '10455', '10475', '10069',
       '10303', '10308', '10302', '11357', '10470', '11367', '11370',
       '10454', '10451', '11436', '11426', '10153', '11004', '11428',
       '11427', '11001', '11363', '10004', '10474', '11430', '10000',
       '10307', '11239', '10119', '10006', '10048', '11697', '11692',
       '11693', '10573', '00083', '11559', '10020', '77056', '11776',
       '70711', '10282', '11109', '10044', '02061', '77092-2016', '14225',
       '55164-0737', '19711', '07306', '000000', '90010', '11747',
       '23541', '11788', '07604', '10112', '11563', '11580', '07087',
       '11042', '07093', '11501', '92123', '00000', '11575', '07109',
       '11797', '10803', '11716', '11722', '11549-3650', '10162', '23502',
       '11518', '07020', '08807', '11577', '07114', '11003', '07201',
       '61702', '10103', '29616-0759', '35209-3114', '11520', '11735',
       '10129', '11005', '41042', '11590', '06901', '07208', '11530',
       '13221', '10954', '11111', '10107'], dtype=object)

# 7.3 What's up with the dashes?

In [55]:
rows_with_dashes = df['Incident Zip'].str.contains('-').fillna(False)

In [59]:
rows_with_dashes

0         False
1         False
2         False
3         False
4         False
          ...
111064    False
111065    False
111066    False
111067    False
111068    False
Name: Incident Zip, Length: 111069, dtype: bool

In [60]:
df[rows_with_dashes]

       Unique Key            Created Date             Closed Date Agency                     Agency Name      Complaint Type         Descriptor Location Type Incident Zip        Incident Address         Street Name Cross Street 1 Cross Street 2 Intersection Street 1 Intersection Street 2 Address Type        City Landmark Facility Type    Status                Due Date Resolution Action Updated Date Community Board      Borough  X Coordinate (State Plane)  Y Coordinate (State Plane) Park Facility Name Park Borough  School Name School Number School Region  School Code School Phone Number School Address  School City School State   School Zip School Not Found  School or Citywide Complaint Vehicle Type Taxi Company Borough Taxi Pick Up Location Bridge Highway Name Bridge Highway Direction Road Ramp Bridge Highway Segment Garage Lot Name Ferry Direction Ferry Terminal Name  Latitude  Longitude Location
29136    26550551  10/24/2013 06:16:34 PM                     NaN    DCA  Department of Consumer Affairs  Consumer Complaint  False Advertising           NaN   77092-2016   2700 EAST SELTICE WAY    EAST SELTICE WAY            NaN            NaN                   NaN                   NaN          NaN     HOUSTON      NaN           NaN  Assigned  11/13/2013 11:15:20 AM         10/29/2013 11:16:16 AM   0 Unspecified  Unspecified                         NaN                         NaN        Unspecified  Unspecified  Unspecified   Unspecified   Unspecified  Unspecified         Unspecified    Unspecified  Unspecified  Unspecified  Unspecified                N                           NaN          NaN                  NaN                   NaN                 NaN                      NaN       NaN                    NaN             NaN             NaN                 NaN       NaN        NaN      NaN
30939    26548831  10/24/2013 09:35:10 AM                     NaN    DCA  Department of Consumer Affairs  Consumer Complaint         Harassment           NaN   55164-0737          P.O. BOX 64437               64437            NaN            NaN                   NaN                   NaN          NaN    ST. PAUL      NaN           NaN  Assigned  11/13/2013 02:30:21 PM         10/29/2013 02:31:06 PM   0 Unspecified  Unspecified                         NaN                         NaN        Unspecified  Unspecified  Unspecified   Unspecified   Unspecified  Unspecified         Unspecified    Unspecified  Unspecified  Unspecified  Unspecified                N                           NaN          NaN                  NaN                   NaN                 NaN                      NaN       NaN                    NaN             NaN             NaN                 NaN       NaN        NaN      NaN
70539    26488417  10/15/2013 03:40:33 PM                     NaN    TLC   Taxi and Limousine Commission      Taxi Complaint   Driver Complaint        Street   11549-3650  365 HOFSTRA UNIVERSITY  HOFSTRA UNIVERSITY            NaN            NaN                   NaN                   NaN          NaN    HEMSTEAD      NaN           NaN  Assigned  11/30/2013 01:20:33 PM         10/16/2013 01:21:39 PM   0 Unspecified  Unspecified                         NaN                         NaN        Unspecified  Unspecified  Unspecified   Unspecified   Unspecified  Unspecified         Unspecified    Unspecified  Unspecified  Unspecified  Unspecified                N                           NaN          NaN                  NaN    La Guardia Airport                 NaN                      NaN       NaN                    NaN             NaN             NaN                 NaN       NaN        NaN      NaN
85821    26468296  10/10/2013 12:36:43 PM  10/26/2013 01:07:07 AM    DCA  Department of Consumer Affairs  Consumer Complaint      Debt Not Owed           NaN   29616-0759            PO BOX 25759           BOX 25759            NaN            NaN                   NaN                   NaN          NaN  GREENVILLE      NaN           NaN    Closed  10/26/2013 09:20:28 AM         10/26/2013 01:07:07 AM   0 Unspecified  Unspecified                         NaN                         NaN        Unspecified  Unspecified  Unspecified   Unspecified   Unspecified  Unspecified         Unspecified    Unspecified  Unspecified  Unspecified  Unspecified                N                           NaN          NaN                  NaN                   NaN                 NaN                      NaN       NaN                    NaN             NaN             NaN                 NaN       NaN        NaN      NaN
89304    26461137  10/09/2013 05:23:46 PM  10/25/2013 01:06:41 AM    DCA  Department of Consumer Affairs  Consumer Complaint         Harassment           NaN   35209-3114         600 BEACON PKWY         BEACON PKWY            NaN            NaN                   NaN                   NaN          NaN  BIRMINGHAM      NaN           NaN    Closed  10/25/2013 02:43:42 PM         10/25/2013 01:06:41 AM   0 Unspecified  Unspecified                         NaN                         NaN        Unspecified  Unspecified  Unspecified   Unspecified   Unspecified  Unspecified         Unspecified    Unspecified  Unspecified  Unspecified  Unspecified                N                           NaN          NaN                  NaN                   NaN                 NaN                      NaN       NaN                    NaN             NaN             NaN                 NaN       NaN        NaN      NaN

In [61]:
long_zip_codes = df['Incident Zip'].str.len()>5

In [62]:
long_zip_codes

0         False
1         False
2         False
3         False
4         False
          ...
111064    False
111065    False
111066    False
111067    False
111068    False
Name: Incident Zip, Length: 111069, dtype: bool

In [64]:
df['Incident Zip'][long_zip_codes].unique()

array(['77092-2016', '55164-0737', '000000', '11549-3650', '29616-0759',
       '35209-3114'], dtype=object)

In [65]:
df['Incident Zip'] = df['Incident Zip'].str.slice(0, 5)

In [67]:
df[df['Incident Zip'] == '00000']

       Unique Key            Created Date Closed Date Agency                    Agency Name  Complaint Type        Descriptor Location Type Incident Zip  Incident Address     Street Name Cross Street 1 Cross Street 2 Intersection Street 1 Intersection Street 2 Address Type    City Landmark Facility Type    Status                Due Date Resolution Action Updated Date Community Board      Borough  X Coordinate (State Plane)  Y Coordinate (State Plane) Park Facility Name Park Borough  School Name School Number School Region  School Code School Phone Number School Address  School City School State   School Zip School Not Found  School or Citywide Complaint Vehicle Type Taxi Company Borough Taxi Pick Up Location Bridge Highway Name Bridge Highway Direction Road Ramp Bridge Highway Segment Garage Lot Name Ferry Direction Ferry Terminal Name  Latitude  Longitude Location
42600    26529313  10/22/2013 02:51:06 PM         NaN    TLC  Taxi and Limousine Commission  Taxi Complaint  Driver Complaint           NaN        00000           EWR EWR             EWR            NaN            NaN                   NaN                   NaN          NaN  NEWARK      NaN           NaN  Assigned  12/07/2013 09:53:51 AM         10/23/2013 09:54:43 AM   0 Unspecified  Unspecified                         NaN                         NaN        Unspecified  Unspecified  Unspecified   Unspecified   Unspecified  Unspecified         Unspecified    Unspecified  Unspecified  Unspecified  Unspecified                N                           NaN          NaN                  NaN                 Other                 NaN                      NaN       NaN                    NaN             NaN             NaN                 NaN       NaN        NaN      NaN
60843    26507389  10/17/2013 05:48:44 PM         NaN    TLC  Taxi and Limousine Commission  Taxi Complaint  Driver Complaint        Street        00000  1 NEWARK AIRPORT  NEWARK AIRPORT            NaN            NaN                   NaN                   NaN          NaN  NEWARK      NaN           NaN  Assigned  12/02/2013 11:59:46 AM         10/18/2013 12:01:08 PM   0 Unspecified  Unspecified                         NaN                         NaN        Unspecified  Unspecified  Unspecified   Unspecified   Unspecified  Unspecified         Unspecified    Unspecified  Unspecified  Unspecified  Unspecified                N                           NaN          NaN                  NaN                 Other                 NaN                      NaN       NaN                    NaN             NaN             NaN                 NaN       NaN        NaN      NaN

In [68]:
zero_zips = df['Incident Zip'] == '00000'

In [70]:
df.loc[zero_zips, 'Incident Zip'] = np.nan

In [71]:
unique_zips = df['Incident Zip'].unique()

In [72]:
unique_zips

array(['11432', '11378', '10032', '10023', '10027', '11372', '11419',
       '11417', '10011', '11225', '11218', '10003', '10029', '10466',
       '11219', '10025', '10310', '11236', nan, '10033', '11216', '10016',
       '10305', '10312', '10026', '10309', '10036', '11433', '11235',
       '11213', '11379', '11101', '10014', '11231', '11234', '10457',
       '10459', '10465', '11207', '10002', '10034', '11233', '10453',
       '10456', '10469', '11374', '11221', '11421', '11215', '10007',
       '10019', '11205', '11418', '11369', '11249', '10005', '10009',
       '11211', '11412', '10458', '11229', '10065', '10030', '11222',
       '10024', '10013', '11420', '11365', '10012', '11214', '11212',
       '10022', '11232', '11040', '11226', '10281', '11102', '11208',
       '10001', '10472', '11414', '11223', '10040', '11220', '11373',
       '11203', '11691', '11356', '10017', '10452', '10280', '11217',
       '10031', '11201', '11358', '10128', '11423', '10039', '10010',
       '11209', '10021', '10037', '11413', '11375', '11238', '10473',
       '11103', '11354', '11361', '11106', '11385', '10463', '10467',
       '11204', '11237', '11377', '11364', '11434', '11435', '11210',
       '11228', '11368', '11694', '10464', '11415', '10314', '10301',
       '10018', '10038', '11105', '11230', '10468', '11104', '10471',
       '11416', '10075', '11422', '11355', '10028', '10462', '10306',
       '10461', '11224', '11429', '10035', '11366', '11362', '11206',
       '10460', '10304', '11360', '11411', '10455', '10475', '10069',
       '10303', '10308', '10302', '11357', '10470', '11367', '11370',
       '10454', '10451', '11436', '11426', '10153', '11004', '11428',
       '11427', '11001', '11363', '10004', '10474', '11430', '10000',
       '10307', '11239', '10119', '10006', '10048', '11697', '11692',
       '11693', '10573', '00083', '11559', '10020', '77056', '11776',
       '70711', '10282', '11109', '10044', '02061', '77092', '14225',
       '55164', '19711', '07306', '90010', '11747', '23541', '11788',
       '07604', '10112', '11563', '11580', '07087', '11042', '07093',
       '11501', '92123', '11575', '07109', '11797', '10803', '11716',
       '11722', '11549', '10162', '23502', '11518', '07020', '08807',
       '11577', '07114', '11003', '07201', '61702', '10103', '29616',
       '35209', '11520', '11735', '10129', '11005', '41042', '11590',
       '06901', '07208', '11530', '13221', '10954', '11111', '10107'],
      dtype=object)

In [73]:
zips = df['Incident Zip']
is_close = zips.str.startswith('0') | zips.str.startswith('1')
is_far = ~(is_close) & zips.notnull()

In [74]:
is_close

0         True
1         True
2         True
3         True
4         True
          ...
111064    True
111065    True
111066    True
111067    True
111068    True
Name: Incident Zip, Length: 111069, dtype: bool

In [75]:
is_far

0         False
1         False
2         False
3         False
4         False
          ...
111064    False
111065    False
111066    False
111067    False
111068    False
Name: Incident Zip, Length: 111069, dtype: bool

In [77]:
df[is_close][['Incident Zip', 'Descriptor', 'City']]

       Incident Zip                     Descriptor      City
0             11432                   Loud Talking   JAMAICA
1             11378   Commercial Overnight Parking   MASPETH
2             10032               Loud Music/Party  NEW YORK
3             10023                 Car/Truck Horn  NEW YORK
4             10027   Condition Attracting Rodents  NEW YORK
...             ...                            ...       ...
111064        11213           Structure - Outdoors  BROOKLYN
111065        11434  Posted Parking Sign Violation   JAMAICA
111066        10016                   Loud Talking  NEW YORK
111067        11226                   Loud Talking  BROOKLYN
111068        11236                 Partial Access  BROOKLYN

[98791 rows x 3 columns]